server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/product-api
    username: supermolecula
    password: qwerty1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true